spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/hanaro
    username: sophia
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/hanaro
#    username: sophia
#    password: kimjihye4352
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    username: tnals00718@gmail.com  # 자신의 이메일
    password: iwnqywblxcmfbmgy      # 앱 비밀번호
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: true

naver:
  url: https://openapi.naver.com/v1/search/news.json
  client-id: oez4pqzqSQo6bLI9dQsA
  client-secret: hbz7_dGu2d



logging:
  level:
    org:
      springframework:
        security=DEBUG:



app:
  appkey: "PSA60aQNb0Bb4QC28GYKzwvzg09Grn4p6R43"
  appsecret: "EZw6CsYLPGUpPoO/AZMamCoZIByDzkBoQmn0gS6uD3tw9wz8uDH0JoQEQLGeFPpq448D5+nl8yFJFCvcOGZCrCPrQlhLjU56H37db8DRy5gWA4LUNYiTQHF9wCIpwXzFBguvE4CY4oTRNrEdiVYum8w8deObyObIsnxVH46YXD/EMpiP1fs="